// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBA.Models.DataContext;

namespace NBA.Models.Migrations
{
    [DbContext(typeof(NBAContext))]
    [Migration("20211002205247_NBA.v025")]
    partial class NBAv025
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NBA.Models.Entities.FullSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBenchPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFastBreakPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPITP")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayPointsofTO")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTotalRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<int?>("GameDateId")
                        .HasColumnType("int");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBenchPoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFastBreakPoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePITP")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomePointsofTO")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTotalRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.Property<bool>("OverTime")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameDateId");

                    b.ToTable("FullSeason");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeason19_20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBenchPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFastBreakPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPITP")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayPointsofTO")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTotalRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<int?>("GameDateId")
                        .HasColumnType("int");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBenchPoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFastBreakPoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePITP")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomePointsofTO")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTotalRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.Property<bool>("OverTime")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameDateId");

                    b.ToTable("FullSeason19_20");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeason20_21", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBenchPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFastBreakPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPITP")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwayPointsofTO")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTotalRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<int?>("GameDateId")
                        .HasColumnType("int");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBenchPoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFastBreakPoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePITP")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomePointsofTO")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTotalRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.Property<bool>("OverTime")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GameDateId");

                    b.ToTable("FullSeason20_21");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeasonQuarters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("QuarterNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FullSeasonQuarters");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeasonQuarters19_20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("QuarterNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FullSeasonQuarters19_20");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeasonQuarters20_21", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("QuarterNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FullSeasonQuarters20_21");
                });

            modelBuilder.Entity("NBA.Models.Entities.GamePredictions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<bool>("FirstGame")
                        .HasColumnType("bit");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GamePredictions");
                });

            modelBuilder.Entity("NBA.Models.Entities.GameTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameTime");
                });

            modelBuilder.Entity("NBA.Models.Entities.GameTime19_20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameTime19_20");
                });

            modelBuilder.Entity("NBA.Models.Entities.GameTime20_21", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameTime20_21");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<double>("Player3PA")
                        .HasColumnType("float");

                    b.Property<double>("Player3PM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerAssists")
                        .HasColumnType("float");

                    b.Property<double>("PlayerBlocks")
                        .HasColumnType("float");

                    b.Property<double>("PlayerDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFouls")
                        .HasColumnType("float");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("PlayerOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPoints")
                        .HasColumnType("float");

                    b.Property<double>("PlayerSteals")
                        .HasColumnType("float");

                    b.Property<double>("PlayerTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStats19_20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<double>("Player3PA")
                        .HasColumnType("float");

                    b.Property<double>("Player3PM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerAssists")
                        .HasColumnType("float");

                    b.Property<double>("PlayerBlocks")
                        .HasColumnType("float");

                    b.Property<double>("PlayerDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFouls")
                        .HasColumnType("float");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("PlayerOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPoints")
                        .HasColumnType("float");

                    b.Property<double>("PlayerSteals")
                        .HasColumnType("float");

                    b.Property<double>("PlayerTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStats19_20");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStats20_21", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<double>("Player3PA")
                        .HasColumnType("float");

                    b.Property<double>("Player3PM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerAssists")
                        .HasColumnType("float");

                    b.Property<double>("PlayerBlocks")
                        .HasColumnType("float");

                    b.Property<double>("PlayerDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFouls")
                        .HasColumnType("float");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("PlayerOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPoints")
                        .HasColumnType("float");

                    b.Property<double>("PlayerSteals")
                        .HasColumnType("float");

                    b.Property<double>("PlayerTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStats20_21");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStatsQuarter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<double>("Player3PA")
                        .HasColumnType("float");

                    b.Property<double>("Player3PM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerAssists")
                        .HasColumnType("float");

                    b.Property<double>("PlayerBlocks")
                        .HasColumnType("float");

                    b.Property<double>("PlayerDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFouls")
                        .HasColumnType("float");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("PlayerOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPoints")
                        .HasColumnType("float");

                    b.Property<double>("PlayerSteals")
                        .HasColumnType("float");

                    b.Property<double>("PlayerTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("QuarterNo")
                        .HasColumnType("int");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStatsQuarter");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStatsQuarter19_20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<double>("Player3PA")
                        .HasColumnType("float");

                    b.Property<double>("Player3PM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerAssists")
                        .HasColumnType("float");

                    b.Property<double>("PlayerBlocks")
                        .HasColumnType("float");

                    b.Property<double>("PlayerDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFouls")
                        .HasColumnType("float");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("PlayerOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPoints")
                        .HasColumnType("float");

                    b.Property<double>("PlayerSteals")
                        .HasColumnType("float");

                    b.Property<double>("PlayerTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStatsQuarter19_20");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStatsQuarter20_21", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<double>("Player3PA")
                        .HasColumnType("float");

                    b.Property<double>("Player3PM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerAssists")
                        .HasColumnType("float");

                    b.Property<double>("PlayerBlocks")
                        .HasColumnType("float");

                    b.Property<double>("PlayerDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFGM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTA")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFTM")
                        .HasColumnType("float");

                    b.Property<double>("PlayerFouls")
                        .HasColumnType("float");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("PlayerOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPlusMinus")
                        .HasColumnType("float");

                    b.Property<double>("PlayerPoints")
                        .HasColumnType("float");

                    b.Property<double>("PlayerSteals")
                        .HasColumnType("float");

                    b.Property<double>("PlayerTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStatsQuarter20_21");
                });

            modelBuilder.Entity("NBA.Models.Entities.QuarterPredictions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Away3PA")
                        .HasColumnType("float");

                    b.Property<double>("Away3PM")
                        .HasColumnType("float");

                    b.Property<double>("AwayAssists")
                        .HasColumnType("float");

                    b.Property<double>("AwayBlocks")
                        .HasColumnType("float");

                    b.Property<double>("AwayDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFGM")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTA")
                        .HasColumnType("float");

                    b.Property<double>("AwayFTM")
                        .HasColumnType("float");

                    b.Property<double>("AwayOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("AwayPoints")
                        .HasColumnType("float");

                    b.Property<double>("AwaySteals")
                        .HasColumnType("float");

                    b.Property<int>("AwayTeam")
                        .HasColumnType("int");

                    b.Property<double>("AwayTurnovers")
                        .HasColumnType("float");

                    b.Property<bool>("FirstGame")
                        .HasColumnType("bit");

                    b.Property<int>("GameNo")
                        .HasColumnType("int");

                    b.Property<double>("Home3PA")
                        .HasColumnType("float");

                    b.Property<double>("Home3PM")
                        .HasColumnType("float");

                    b.Property<double>("HomeAssists")
                        .HasColumnType("float");

                    b.Property<double>("HomeBlocks")
                        .HasColumnType("float");

                    b.Property<double>("HomeDefensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFGM")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTA")
                        .HasColumnType("float");

                    b.Property<double>("HomeFTM")
                        .HasColumnType("float");

                    b.Property<double>("HomeOffensiveRebounds")
                        .HasColumnType("float");

                    b.Property<double>("HomePoints")
                        .HasColumnType("float");

                    b.Property<double>("HomeSteals")
                        .HasColumnType("float");

                    b.Property<int>("HomeTeam")
                        .HasColumnType("int");

                    b.Property<double>("HomeTurnovers")
                        .HasColumnType("float");

                    b.Property<int>("QuarterNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuarterPredictions");
                });

            modelBuilder.Entity("NBA.Models.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NBA.Models.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Conference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeason", b =>
                {
                    b.HasOne("NBA.Models.Entities.GameTime", "GameDate")
                        .WithMany()
                        .HasForeignKey("GameDateId");

                    b.Navigation("GameDate");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeason19_20", b =>
                {
                    b.HasOne("NBA.Models.Entities.GameTime19_20", "GameDate")
                        .WithMany()
                        .HasForeignKey("GameDateId");

                    b.Navigation("GameDate");
                });

            modelBuilder.Entity("NBA.Models.Entities.FullSeason20_21", b =>
                {
                    b.HasOne("NBA.Models.Entities.GameTime20_21", "GameDate")
                        .WithMany()
                        .HasForeignKey("GameDateId");

                    b.Navigation("GameDate");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStats", b =>
                {
                    b.HasOne("NBA.Models.Players", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStats19_20", b =>
                {
                    b.HasOne("NBA.Models.Players", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStats20_21", b =>
                {
                    b.HasOne("NBA.Models.Players", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStatsQuarter", b =>
                {
                    b.HasOne("NBA.Models.Players", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStatsQuarter19_20", b =>
                {
                    b.HasOne("NBA.Models.Players", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NBA.Models.Entities.PlayerStatsQuarter20_21", b =>
                {
                    b.HasOne("NBA.Models.Players", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
