//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBA.Services.Abstraction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NBA.Services.Abstraction.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresiniz zaten onaylamış durumda.
        /// </summary>
        internal static string AlreadyConfirmedEmail {
            get {
                return ResourceManager.GetString("AlreadyConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basit Hesap.
        /// </summary>
        internal static string Basic_Account {
            get {
                return ResourceManager.GetString("Basic_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik bilgileriniz doğrulanamadı.
        /// </summary>
        internal static string CannotVerifyIdentity {
            get {
                return ResourceManager.GetString("CannotVerifyIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;h3&gt;Merhaba , E-posta adresinizi doğrulamak için lütfen 
        ///    &lt;a href=&quot;&lt;%=url%&gt;&quot;&gt;tıklayınız&lt;/a&gt;
        ///&lt;/h3&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ChangeMailConfirmationMailTemp {
            get {
                return ResourceManager.GetString("ChangeMailConfirmationMailTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylı Hesap.
        /// </summary>
        internal static string Confirmed_Account {
            get {
                return ResourceManager.GetString("Confirmed_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylı.
        /// </summary>
        internal static string ConfirmedEmail {
            get {
                return ResourceManager.GetString("ConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir hata oluştu. Ekibimiz konu ile ilgili bilgilendirildi. Lütfen daha sonra tekrar deneyiniz..
        /// </summary>
        internal static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresiniz onaylanamadı. Lütfen hesabınıza giriş yapıp yeni bir onay isteğinde bulunun..
        /// </summary>
        internal static string ErrorConfirmEmail {
            get {
                return ResourceManager.GetString("ErrorConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlemi gerçekleştirmek için yetkiniz yok. Lütfen destek birimi ile iletişime geçin..
        /// </summary>
        internal static string ForbiddenError {
            get {
                return ResourceManager.GetString("ForbiddenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maç istatistikleri bulunamadı!.
        /// </summary>
        internal static string FullSeasonNotFound {
            get {
                return ResourceManager.GetString("FullSeasonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeyrek istatistikleri bulunamadı!.
        /// </summary>
        internal static string FullSeasonQuarterNotFound {
            get {
                return ResourceManager.GetString("FullSeasonQuarterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maç tarihi bilgileri bulunamadı!.
        /// </summary>
        internal static string GameTimeNotFound {
            get {
                return ResourceManager.GetString("GameTimeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin kodu geçerli değil.
        /// </summary>
        internal static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabım.
        /// </summary>
        internal static string Menu_Account {
            get {
                return ResourceManager.GetString("Menu_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunamadı.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncu bulunamadı!.
        /// </summary>
        internal static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncu istatistikleri bulunamadı!.
        /// </summary>
        internal static string PlayerStatNotFound {
            get {
                return ResourceManager.GetString("PlayerStatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use a Pin that you used previously.
        /// </summary>
        internal static string PreviouslyUsedPin {
            get {
                return ResourceManager.GetString("PreviouslyUsedPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu numara ile kayıtlı bir kullanıcı zaten var..
        /// </summary>
        internal static string RegisteredPhoneNumber {
            get {
                return ResourceManager.GetString("RegisteredPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstek bulunamadı..
        /// </summary>
        internal static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz değiştirilemedi. Lütfen tekrar deneyin..
        /// </summary>
        internal static string ResetPasswordError {
            get {
                return ResourceManager.GetString("ResetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz başarıyla değiştirildi..
        /// </summary>
        internal static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use a Pin containing same digits..
        /// </summary>
        internal static string SameDigitsPin {
            get {
                return ResourceManager.GetString("SameDigitsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail adresinizi onaylamak için e-posta gönderilmiştir.
        /// </summary>
        internal static string SentConfirmationEmail {
            get {
                return ResourceManager.GetString("SentConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;h3&gt;Merhaba , E-posta adresinizi doğrulamak için lütfen tıklayınız. 
        ///    &lt;a href=&apos;&lt;%=url%&gt;&lt;%=userId%&gt;&lt;%=emailConfirmationCode%&gt;&apos;&gt;Doğrula&lt;/a&gt;
        ///&lt;/h3&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SignupConfirmationMailTemp {
            get {
                return ResourceManager.GetString("SignupConfirmationMailTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS gönderilemedi..
        /// </summary>
        internal static string SmsNotSend {
            get {
                return ResourceManager.GetString("SmsNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresiniz onaylanmıştır. Teşekkürler!.
        /// </summary>
        internal static string SuccessConfirmEmail {
            get {
                return ResourceManager.GetString("SuccessConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaysız.
        /// </summary>
        internal static string UnConfirmedEmail {
            get {
                return ResourceManager.GetString("UnConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı zaten kayıtlı.
        /// </summary>
        internal static string UserIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteme erişiminiz kilitlendi. {0} dakika sonra tekrar deneyiniz..
        /// </summary>
        internal static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen e-posta adresini doldurunuz..
        /// </summary>
        internal static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen adınızı girin..
        /// </summary>
        internal static string Validation_FirstName {
            get {
                return ResourceManager.GetString("Validation_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen soyadınızı girin..
        /// </summary>
        internal static string Validation_LastName {
            get {
                return ResourceManager.GetString("Validation_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen şifrenizi girin..
        /// </summary>
        internal static string Validation_Password {
            get {
                return ResourceManager.GetString("Validation_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen şifre tekrarını girin..
        /// </summary>
        internal static string Validation_PasswordAgain {
            get {
                return ResourceManager.GetString("Validation_PasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen telefon numaranızı girin..
        /// </summary>
        internal static string Validation_PhoneNumber {
            get {
                return ResourceManager.GetString("Validation_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kullanım sözleşmesini onaylayın..
        /// </summary>
        internal static string Validation_TermsAndConditions {
            get {
                return ResourceManager.GetString("Validation_TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteme kayıtlı böyle bir e-posta adresi bulunamadı..
        /// </summary>
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı şifre girdiniz. Kalan deneme hakkınız: {0}.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış SMS kodu girdiniz..
        /// </summary>
        internal static string WrongSmsCode {
            get {
                return ResourceManager.GetString("WrongSmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farklı bir e-posta adresi girmelisiniz..
        /// </summary>
        internal static string YouNeedToSendADifferentEmailAddress {
            get {
                return ResourceManager.GetString("YouNeedToSendADifferentEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumunuz sonlandırıldı, lütfen tekrar giriş yapın.
        /// </summary>
        internal static string YourSessionHasBeenFinalizedPleaseLoginAgain {
            get {
                return ResourceManager.GetString("YourSessionHasBeenFinalizedPleaseLoginAgain", resourceCulture);
            }
        }
    }
}
